const sedeSeed = [
  ['sede-centro-mayor', 'Centro Mayor', 'Calle 38A Sur # 34D-51, Antonio Nariño, Bogotá.'],
  ['sede-santa-fe', 'Centro Comercial Santa Fe', 'Autopista Norte con Calle 183, Bogotá.'],
  ['sede-plaza-central', 'Plaza Central', 'Carrera 65 # 11-50, Puente Aranda, Bogotá.'],
  ['sede-mallplaza-nqs', 'Mallplaza NQS', 'Carrera 30 # 19, Los Mártires, Bogotá.'],
  ['sede-nuestro-bogota', 'Nuestro Bogotá', 'Av. Carrera 86 # 55A-75, Engativá, Bogotá.']
];
const spaceSeed = [];
const addSeedSpaces = (sede) => {
  const [sedeId, sedeName] = sede;
  for (let i = 1; i <= 30; i++) spaceSeed.push({ id:`puesto-${sedeId}-${i}`, name:`Puesto ${i}`, location:`${sedeName} · Piso 2, Área abierta`, type:'Escritorio flexible', typeClass:'green', capacity:1, price:12000, dayPrice:45000, status:'Activo', statusClass:'active', icon:'▤', thumb:'desk' });
  for (let i = 1; i <= 15; i++) spaceSeed.push({ id:`oficina-${sedeId}-${i}`, name:`Oficina ${i}`, location:`${sedeName} · Piso 2`, type:'Oficina privada', typeClass:'purple', capacity:2, price:35000, dayPrice:150000, status:'Activo', statusClass:'active', icon:'▦', thumb:'office' });
  for (let i = 1; i <= 10; i++) spaceSeed.push({ id:`cubiculo-${sedeId}-${i}`, name:`Cubículo ${i}`, location:`${sedeName} · Piso 2`, type:'Oficina privada', typeClass:'purple', capacity:4, price:55000, dayPrice:220000, status:'Activo', statusClass:'active', icon:'▦', thumb:'office' });
  for (let i = 1; i <= 3; i++) spaceSeed.push({ id:`sala-alpha-${sedeId}-${i}`, name:`Sala Alpha ${i}`, location:`${sedeName} · Piso 3`, type:'Sala de reunión', typeClass:'blue', capacity:6, price:70000, status:'Activo', statusClass:'active', icon:'▥', thumb:'meeting' });
  for (let i = 1; i <= 2; i++) spaceSeed.push({ id:`sala-beta-${sedeId}-${i}`, name:`Sala Beta ${i}`, location:`${sedeName} · Piso 3`, type:'Sala de reunión', typeClass:'blue', capacity:8, price:95000, status:'Activo', statusClass:'active', icon:'▥', thumb:'meeting' });
  spaceSeed.push({ id:`sala-gamma-${sedeId}`, name:'Sala Gamma', location:`${sedeName} · Piso 3`, type:'Sala de reunión', typeClass:'blue', capacity:12, price:130000, status:'Activo', statusClass:'active', icon:'▥', thumb:'meeting' });
};
sedeSeed.forEach(addSeedSpaces);
const state = {
  spaces: spaceSeed,
  bookings: [
    { id:'RSV-1048', spaceId:'sp-01', space:'Escritorio flexible 01', user:'Mariana Torres', date:'2026-09-10', start:'09:00', end:'13:00', status:'Confirmada', total:72000 },
    { id:'RSV-1047', spaceId:'sp-02', space:'Sala Creativa', user:'Daniel Rojas', date:'2026-09-10', start:'14:00', end:'16:00', status:'Confirmada', total:90000 },
    { id:'RSV-1046', spaceId:'sp-04', space:'Sala Horizonte', user:'Sofía Martínez', date:'2026-09-11', start:'10:00', end:'12:00', status:'Completada', total:120000 }
  ],
  payments: [{ invoice:'FAC-000982', booking:'RSV-1048', user:'Mariana Torres', amount:85680, method:'PSE', status:'Pagado', date:'10 sep 2026' }, { invoice:'FAC-000981', booking:'RSV-1047', user:'Daniel Rojas', amount:107100, method:'Tarjeta', status:'Pagado', date:'10 sep 2026' }],
  plans: [['Básico', 320000, 'Puesto flexible ilimitado en cualquier sede', '5h de salas de reunión'], ['Pro', 580000, 'Puesto flexible ilimitado', 'Oficina privada por horas con descuento', '20h de salas'], ['Empresarial', 1450000, 'Oficina privada dedicada', 'Salas ilimitadas', 'Soporte prioritario']]
};
const $ = (selector) => document.querySelector(selector);
const money = (value) => new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(value);
function render(view='dashboard') {
  const labels = { dashboard:'Resumen', spaces:'Espacios', bookings:'Reservas', payments:'Pagos', locations:'Sedes', members:'Miembros', plans:'Planes' };
  $('#breadcrumb-label').textContent = labels[view];
  document.querySelectorAll('.nav-item[data-view]').forEach(item => item.classList.toggle('active', item.dataset.view === view));
  const views = { dashboard: dashboardView, spaces: spacesView, bookings: bookingsView, payments: paymentsView, locations: locationsView, members: membersView, plans: plansView };
  $('#view-root').innerHTML = views[view]();
  bindViewActions(view);
}
const pageHeading = (title, subtitle, action='') => `<div class="page-heading"><div><h1>${title}</h1><p>${subtitle}</p></div>${action ? `<button class="primary-btn" data-action="${action}">＋ ${action === 'new-space' ? 'Nuevo espacio' : action === 'new-booking' ? 'Nueva reserva' : 'Agregar sede'}</button>` : ''}</div>`;
function dashboardView() { return `<section class="page">${pageHeading('Resumen','Monitorea el rendimiento de tus espacios y reservas.')}
  <div class="kpi-grid"><div class="kpi"><div class="kpi-top">Ingresos este mes <span class="kpi-icon">$</span></div><div class="kpi-value">$18.420.000</div><div class="trend">↗ 12.5% <span>vs. mes anterior</span></div></div><div class="kpi"><div class="kpi-top">Reservas activas <span class="kpi-icon">▣</span></div><div class="kpi-value">248</div><div class="trend">↗ 8.2% <span>vs. mes anterior</span></div></div><div class="kpi"><div class="kpi-top">Espacios ocupados <span class="kpi-icon">▦</span></div><div class="kpi-value">76%</div><div class="trend">↗ 4.8% <span>vs. mes anterior</span></div></div><div class="kpi"><div class="kpi-top">Nuevos miembros <span class="kpi-icon">♙</span></div><div class="kpi-value">36</div><div class="trend">↗ 16.4% <span>vs. mes anterior</span></div></div></div>
  <div class="section-head"><h2>Espacios destacados</h2><button class="text-link" data-view-link="spaces">Ver todos →</button></div><div class="panel table-wrap">${spacesTable(state.spaces.slice(0,4))}</div></section>`; }
function spacesTable(spaces) { return `<table class="data-table"><thead><tr><th>Espacio</th><th>Tipo</th><th>Capacidad</th><th>Precio / hora</th><th>Estado</th></tr></thead><tbody>${spaces.map(s=>`<tr><td><div class="space-cell"><div class="thumb ${s.thumb}">${s.icon}</div><div><span class="space-name">${s.name}</span><span class="space-location">${s.location}</span></div></div></td><td><span class="type-chip ${s.typeClass}">${s.type}</span></td><td>${s.capacity} ${s.capacity === 1 ? 'persona' : 'personas'}</td><td>${money(s.price)}</td><td><span class="status ${s.statusClass}">${s.status}</span></td></tr>`).join('')}</tbody></table>`; }
function spacesView() { return `<section class="page">${pageHeading('Espacios',`${state.spaces.length} espacios disponibles en 5 sedes.`,'new-space')}<div class="toolbar"><input class="search" id="space-search" placeholder="⌕  Buscar espacio..." type="search"><select class="filter-select" id="space-filter"><option value="all">Todos los estados</option><option value="active">Activos</option><option value="maintenance">En mantenimiento</option></select></div><div class="panel table-wrap" id="spaces-table">${spacesTable(state.spaces)}</div></section>`; }
function bookingsView() { return `<section class="page">${pageHeading('Reservas','Consulta y controla las reservas de todas las sedes.','new-booking')}<div class="view-tabs"><button class="active">Todas</button><button>Confirmadas</button><button>Completadas</button><button>Canceladas</button></div><div class="panel table-wrap"><table class="data-table"><thead><tr><th>Reserva</th><th>Espacio</th><th>Fecha y horario</th><th>Cliente</th><th>Total</th><th>Estado</th></tr></thead><tbody>${state.bookings.map(b=>`<tr><td><strong>${b.id}</strong></td><td>${b.space}</td><td>${b.date}<span class="space-location">${b.start} - ${b.end}</span></td><td>${b.user}</td><td>${money(b.total)}</td><td><span class="status ${b.status==='Confirmada'?'active':b.status==='Completada'?'active':'inactive'}">${b.status}</span></td></tr>`).join('')}</tbody></table></div></section>`; }
function paymentsView() { return `<section class="page">${pageHeading('Pagos','Revisa transacciones, facturas y estados de pago.')}<div class="kpi-grid"><div class="kpi"><div class="kpi-top">Recaudo del mes <span class="kpi-icon">$</span></div><div class="kpi-value">$18.420.000</div><div class="trend">↗ 12.5% <span>vs. mes anterior</span></div></div><div class="kpi"><div class="kpi-top">Pagos pendientes <span class="kpi-icon">◷</span></div><div class="kpi-value">$1.240.000</div><div class="trend">8 facturas</div></div></div><div class="panel table-wrap"><table class="data-table"><thead><tr><th>Factura</th><th>Reserva</th><th>Cliente</th><th>Monto (IVA incluido)</th><th>Método</th><th>Estado</th></tr></thead><tbody>${state.payments.map(p=>`<tr><td><strong>${p.invoice}</strong><span class="space-location">${p.date}</span></td><td>${p.booking}</td><td>${p.user}</td><td>${money(p.amount)}</td><td>${p.method}</td><td><span class="status active">${p.status}</span></td></tr>`).join('')}</tbody></table></div></section>`; }
function locationsView() { return `<section class="page">${pageHeading('Sedes','Cinco ubicaciones para trabajar cerca de ti.','new-location')}<div class="locations-grid">${sedeSeed.map((s,i)=>`<article class="location-card"><div class="location-photo ${['centro','andino','colina','unico','gran'][i]}"></div><div class="location-body"><h3>${s[1]}</h3><p>⌖ ${s[2]}</p><div><span>61 espacios</span><span class="status active">Abierta</span></div></div></article>`).join('')}</div></section>`; }
function membersView() { return `<section class="page">${pageHeading('Miembros','Gestiona los usuarios y sus planes de membresía.')}<div class="panel empty-panel">La gestión de miembros estará disponible al conectar Firebase Authentication.</div></section>`; }
function plansView() { return `<section class="page">${pageHeading('Planes','Configura las membresías que ofrece CoSpace.')}<div class="plans-grid">${state.plans.map((p,i)=>`<article class="plan-card ${i===1?'featured':''}"><span class="plan-tag">${i===1?'MÁS ELEGIDO':''}</span><h3>${p[0]}</h3><strong>${money(p[1])}<small>/ mes</small></strong>${p.slice(2).map(benefit=>`<p>✓ ${benefit}</p>`).join('')}<button class="text-link">Editar plan →</button></article>`).join('')}</div></section>`; }
function bindViewActions(view) { document.querySelectorAll('[data-view-link]').forEach(el=>el.onclick=()=>render(el.dataset.viewLink)); const action=$('[data-action]'); if(action) action.onclick=()=> view==='spaces' ? createSpace() : view==='bookings' ? createBooking() : showToast('La sede está lista para configurarse.'); const search=$('#space-search'); if(search) search.oninput=()=>{ const term=search.value.toLowerCase(); $('#spaces-table').innerHTML=spacesTable(state.spaces.filter(s=>`${s.name} ${s.location}`.toLowerCase().includes(term))); }; const filter=$('#space-filter'); if(filter) filter.onchange=()=>{ $('#spaces-table').innerHTML=spacesTable(state.spaces.filter(s=>filter.value==='all'||s.statusClass===filter.value)); }; }
function createSpace(){ state.spaces.push({id:`sp-0${state.spaces.length+1}`,name:'Nuevo espacio',location:'Sede por asignar · Piso 1',type:'Escritorio flexible',typeClass:'green',capacity:1,price:18000,status:'Activo',statusClass:'active',icon:'▤',thumb:'desk'}); render('spaces'); showToast('Espacio creado correctamente.'); }
function hasOverlap(spaceId,date,start,end){ return state.bookings.some(b=>b.spaceId===spaceId&&b.date===date&&start<b.end&&end>b.start&&b.status!=='Cancelada'); }
function createBooking(){ const space=state.spaces.find(s=>s.statusClass==='active'); const date='2026-09-12'; if(hasOverlap(space.id,date,'09:00','11:00')) return showToast('Ese horario ya está reservado.'); const subtotal=space.price*2; const total=Math.round(subtotal*1.19); const invoice=`FAC-${String(983+state.payments.length).padStart(6,'0')}`; state.bookings.unshift({id:`RSV-${1049+state.bookings.length}`,spaceId:space.id,space:space.name,user:'Laura Gómez',date,start:'09:00',end:'11:00',status:'Confirmada',total}); state.payments.unshift({invoice,booking:state.bookings[0].id,user:'Laura Gómez',amount:total,method:'PSE',status:'Pagado',date:'10 sep 2026'}); render('bookings'); showToast(`Reserva confirmada. Factura ${invoice} generada con IVA del 19%.`); }
function showToast(message){ const toast=$('#toast'); toast.textContent=message; toast.classList.add('show'); setTimeout(()=>toast.classList.remove('show'),3500); }
document.querySelectorAll('.nav-item[data-view]').forEach(item=>item.onclick=()=>{render(item.dataset.view); $('#sidebar').classList.remove('open');}); $('#mobile-menu').onclick=()=>$('#sidebar').classList.toggle('open'); render();