window.CoSpaceConfig = window.CoSpaceConfig || { apiBaseUrl: window.location.hostname === 'localhost' || window.location.protocol === 'file:' ? 'http://localhost:5050/api' : '/api' };
const API = window.CoSpaceConfig.apiBaseUrl;
const demoUser = { id: 'demo-member', nombre: 'Sebastián Gil', correo: 'sebastian.gil@example.com', telefono: '300 000 0000', rol: 0, planId: 'plan-pro', sedePreferidaId: 'sede-centro-mayor' };
const locations = [['sede-centro-mayor','Centro Mayor'],['sede-santa-fe','Centro Comercial Santa Fe'],['sede-plaza-central','Plaza Central'],['sede-mallplaza-nqs','Mallplaza NQS'],['sede-nuestro-bogota','Nuestro Bogotá']];
const planNames = { 'plan-basico': ['Básico', 320000], 'plan-pro': ['Pro', 580000], 'plan-empresarial': ['Empresarial', 1450000] };
const money = value => new Intl.NumberFormat('es-CO', { style:'currency', currency:'COP', maximumFractionDigits:0 }).format(value);
const user = JSON.parse(localStorage.getItem('cospace-user') || 'null') || demoUser;
if (user.rol !== 0 && user.rol !== 'Miembro') location.href = 'auth.html?mode=login';
if (user.rol === 1 || user.rol === 'Administrador') location.href = 'admin.html';
let currentReservations = [];
const fallbackReservations = [
  { id:'rsv-member-0', espacio:{ nombre:'Puesto 1', ubicacion:'Centro Mayor · Piso 2, Área abierta', tipo:0 }, fecha:'2026-09-15', inicio:'09:00', fin:'13:00', estado:0, numeroFactura:null, precioTotal:48000 },
  { id:'rsv-member-41', espacio:{ nombre:'Puesto 12', ubicacion:'Centro Mayor · Piso 2, Área abierta', tipo:0 }, fecha:'2026-08-29', inicio:'14:00', fin:'16:00', estado:1, numeroFactura:'FAC-000741', precioTotal:190400 },
  { id:'rsv-member-46', espacio:{ nombre:'Oficina 2', ubicacion:'Centro Mayor · Piso 2', tipo:1 }, fecha:'2026-08-19', inicio:'09:00', fin:'17:00', estado:1, numeroFactura:'FAC-000728', precioTotal:333200 },
  { id:'rsv-member-71', espacio:{ nombre:'Cubículo 2', ubicacion:'Centro Mayor · Piso 2', tipo:1 }, fecha:'2026-08-06', inicio:'10:00', fin:'12:00', estado:2, numeroFactura:'FAC-000699', precioTotal:166600 },
  { id:'rsv-member-43', espacio:{ nombre:'Sala Alpha 2', ubicacion:'Centro Mayor · Piso 3', tipo:2 }, fecha:'2026-07-22', inicio:'15:00', fin:'17:00', estado:1, numeroFactura:'FAC-000651', precioTotal:226100 },
  { id:'rsv-member-56', espacio:{ nombre:'Sala Beta 1', ubicacion:'Centro Mayor · Piso 3', tipo:2 }, fecha:'2026-07-14', inicio:'09:00', fin:'18:00', estado:1, numeroFactura:'FAC-000640', precioTotal:416500 }
];
function initials(name) { return name.split(' ').slice(0,2).map(word => word[0]).join('').toUpperCase(); }
function date(value) { return new Intl.DateTimeFormat('es-CO', { day:'numeric', month:'short', year:'numeric' }).format(new Date(`${value}T12:00:00`)); }
function reservationStatus(status) { return [{ label:'Confirmada', className:'confirmed' },{ label:'Completada', className:'completed' },{ label:'Cancelada', className:'cancelled' }][status] || { label:status, className:'completed' }; }
function typeClass(type) { return ['desk','office','meeting'][type] || 'desk'; }
function renderProfile(profile) {
  const member = profile?.usuario || user; const plan = profile?.plan || { nombre: planNames[member.planId]?.[0] || 'Básico', precioMes: planNames[member.planId]?.[1] || 320000 };
  document.querySelector('#profile-name').textContent = member.nombre; document.querySelector('#top-name').textContent = member.nombre; document.querySelector('#profile-email').textContent = member.correo; document.querySelector('#profile-avatar').textContent = initials(member.nombre); document.querySelector('#top-avatar').textContent = initials(member.nombre); document.querySelector('#plan-badge').textContent = `♛ Plan ${plan.nombre}`; document.querySelector('#renewal-date').textContent = profile?.fechaRenovacion ? date(profile.fechaRenovacion) : '15 abr. 2026';
  document.querySelector('#edit-name').value = member.nombre; document.querySelector('#edit-email').value = member.correo; document.querySelector('#edit-phone').value = member.telefono || '';
  const select = document.querySelector('#edit-location'); select.innerHTML = locations.map(([id,name]) => `<option value="${id}" ${id === member.sedePreferidaId ? 'selected' : ''}>${name}</option>`).join('');
}
function renderReservations(reservations) {
  currentReservations = reservations; document.querySelector('#reservations-body').innerHTML = reservations.slice().sort((a,b) => b.fecha.localeCompare(a.fecha)).map(reservation => { const status = reservationStatus(reservation.estado); const future = new Date(`${reservation.fecha}T23:59:00`) > new Date() && status.label === 'Confirmada'; return `<tr><td><div class="space-cell"><div class="space-thumb ${typeClass(reservation.espacio.tipo)}"></div><div><span class="space-name">${reservation.espacio.nombre}</span><span class="space-location">⌖ ${reservation.espacio.ubicacion}</span></div></div></td><td>${date(reservation.fecha)}</td><td>${reservation.inicio} - ${reservation.fin}</td><td><span class="status ${status.className}">${status.label}</span></td><td><button class="action-button" data-invoice="${reservation.id}">◉ &nbsp; Ver detalle</button>${future ? `<button class="action-button cancel-button" data-cancel="${reservation.id}">Cancelar</button>` : ''}</td></tr>`; }).join('');
}
function renderPayment(payment) { if (!payment) return; document.querySelector('#payment-amount').textContent = money(payment.monto); document.querySelector('#payment-date').textContent = date(payment.fecha.slice(0,10)); document.querySelector('#payment-method').textContent = payment.metodo === 0 ? 'Tarjeta de crédito' : payment.metodo === 1 ? 'PSE' : 'Billetera digital'; document.querySelector('#payment-invoice').textContent = payment.numeroFactura; document.querySelector('#download-payment').dataset.reservation = payment.reservaId; }
async function load() { let profile, reservations, payment; try { const [profileResponse, reservationsResponse, paymentResponse] = await Promise.all([fetch(`${API}/perfil/${user.id}`), fetch(`${API}/perfil/${user.id}/reservas`), fetch(`${API}/perfil/${user.id}/pago-ultimo`)]); if (!profileResponse.ok) throw new Error(); profile = await profileResponse.json(); reservations = await reservationsResponse.json(); payment = paymentResponse.status === 204 ? null : await paymentResponse.json(); } catch { profile = null; reservations = fallbackReservations; payment = { monto:580000, fecha:'2026-03-10T00:00:00Z', metodo:0, numeroFactura:'FAC-000741', reservaId:'rsv-member-41' }; } renderProfile(profile); renderReservations(reservations); renderPayment(payment); }
async function downloadInvoice(reservationId) { try { const response = await fetch(`${API}/perfil/${user.id}/reservas/${reservationId}/factura`); if (!response.ok) throw new Error(); const blob = await response.blob(); saveBlob(blob, `factura-${reservationId}.txt`); } catch { const reservation = currentReservations.find(item => item.id === reservationId); const text = `Factura CoSpace\nReserva: ${reservation?.espacio.nombre}\nUbicación: ${reservation?.espacio.ubicacion}\nTotal: ${money(reservation?.precioTotal || 0)}`; saveBlob(new Blob([text], { type:'text/plain' }), `factura-${reservationId}.txt`); } }
function saveBlob(blob, name) { const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = name; link.click(); URL.revokeObjectURL(link.href); }
document.querySelector('#reservations-body').addEventListener('click', async event => { const invoice = event.target.closest('[data-invoice]'); if (invoice) downloadInvoice(invoice.dataset.invoice); const cancel = event.target.closest('[data-cancel]'); if (cancel && confirm('¿Quieres cancelar esta reserva futura?')) { try { const response = await fetch(`${API}/perfil/${user.id}/reservas/${cancel.dataset.cancel}/cancelar`, { method:'POST' }); if (!response.ok) throw new Error(); } catch { const item = currentReservations.find(reservation => reservation.id === cancel.dataset.cancel); if (item) item.estado = 2; } renderReservations(currentReservations); } });
document.querySelector('#download-payment').addEventListener('click', () => downloadInvoice(document.querySelector('#download-payment').dataset.reservation));
document.querySelector('#edit-profile').addEventListener('click', () => document.querySelector('#edit-modal').classList.add('open')); document.querySelector('#close-modal').addEventListener('click', () => document.querySelector('#edit-modal').classList.remove('open'));
document.querySelector('#edit-form').addEventListener('submit', async event => { event.preventDefault(); const data = { nombre:document.querySelector('#edit-name').value, telefono:document.querySelector('#edit-phone').value, sedePreferidaId:document.querySelector('#edit-location').value }; try { const response = await fetch(`${API}/perfil/${user.id}`, { method:'PATCH', headers:{'Content-Type':'application/json'}, body:JSON.stringify(data) }); if (!response.ok) throw new Error(); const updated = await response.json(); localStorage.setItem('cospace-user', JSON.stringify({...user,...updated})); renderProfile({ usuario:{...user,...updated}, plan:null }); document.querySelector('#edit-modal').classList.remove('open'); } catch { Object.assign(user, data); localStorage.setItem('cospace-user', JSON.stringify(user)); renderProfile({ usuario:user, plan:null }); document.querySelector('#edit-modal').classList.remove('open'); } });
document.querySelector('#logout').addEventListener('click', () => { localStorage.removeItem('cospace-authenticated'); localStorage.removeItem('cospace-user'); });
load();
