window.CoSpaceConfig = window.CoSpaceConfig || { apiBaseUrl: 'http://localhost:5050/api' };
const API = window.CoSpaceConfig.apiBaseUrl;
const sedeOptions = [['sede-centro-mayor','Centro Mayor'],['sede-santa-fe','Centro Comercial Santa Fe'],['sede-plaza-central','Plaza Central'],['sede-mallplaza-nqs','Mallplaza NQS'],['sede-nuestro-bogota','Nuestro Bogotá']];
const catalog = [];
const spaces = (sedeId, sedeName) => { for (let i=1;i<=30;i++) catalog.push({ sedeId, id:`puesto-${sedeId}-${i}`,name:`Puesto ${i}`,type:'desk',typeLabel:'Puesto flexible',capacity:1,price:12000,location:`${sedeName} · Piso 2, Área abierta` }); for (let i=1;i<=15;i++) catalog.push({sedeId,id:`oficina-${sedeId}-${i}`,name:`Oficina ${i}`,type:'office',typeLabel:'Oficina privada',capacity:2,price:35000,location:`${sedeName} · Piso 2`}); for (let i=1;i<=10;i++) catalog.push({sedeId,id:`cubiculo-${sedeId}-${i}`,name:`Cubículo ${i}`,type:'cubicle',typeLabel:'Cubículo',capacity:4,price:55000,location:`${sedeName} · Piso 2`}); for (let i=1;i<=3;i++) catalog.push({sedeId,id:`alpha-${sedeId}-${i}`,name:`Sala Alpha ${i}`,type:'meeting',typeLabel:'Sala de reunión',capacity:6,price:70000,location:`${sedeName} · Piso 3`}); for (let i=1;i<=2;i++) catalog.push({sedeId,id:`beta-${sedeId}-${i}`,name:`Sala Beta ${i}`,type:'meeting',typeLabel:'Sala de reunión',capacity:8,price:95000,location:`${sedeName} · Piso 3`}); catalog.push({sedeId,id:`gamma-${sedeId}`,name:'Sala Gamma',type:'meeting',typeLabel:'Sala de reunión',capacity:12,price:130000,location:`${sedeName} · Piso 3`}); };
sedeOptions.forEach(([id,name])=>spaces(id,name));
const sharedSpaces = JSON.parse(localStorage.getItem('cospace-spaces') || 'null');
if (sharedSpaces) { catalog.length = 0; sharedSpaces.forEach(space => catalog.push(space)); }
const times = ['09:00','10:00','11:00','14:00','15:00','16:00']; const params = new URLSearchParams(location.search); const user = JSON.parse(localStorage.getItem('cospace-user') || 'null') || { id:'demo-member', nombre:'Sebastián Gil' }; let selected = null; let occupied = new Set();
const locationFilter=document.querySelector('#location-filter'), typeFilter=document.querySelector('#type-filter'), dateFilter=document.querySelector('#date-filter'), timeFilter=document.querySelector('#time-filter'), grid=document.querySelector('#availability-grid');
locationFilter.innerHTML=sedeOptions.map(([id,name])=>`<option value="${id}">${name}</option>`).join(''); locationFilter.value=params.get('location') && sedeOptions.some(item=>item[0]===params.get('location')) ? params.get('location') : 'sede-centro-mayor';
if(params.get('tipo')) { const typeMap={'Escritorio flexible':'desk','Oficina privada':'office','Cubículo':'cubicle','Sala de reunión':'meeting'}; typeFilter.value=typeMap[params.get('tipo')] || params.get('tipo'); }
const today = new Date(); dateFilter.value = params.get('fecha') || today.toISOString().slice(0,10); document.querySelector('#user-name').textContent=user.nombre || 'Sebastián Gil';
const money=value=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(value);
function localOccupied(spaceId, slot) { return (spaceId.endsWith('-1') && slot === '11:00') || (spaceId.endsWith('-2') && slot === '14:00'); }
async function refreshAvailability() { selected=null; occupied=new Set(); const date=dateFilter.value; try { const response=await fetch(`${API}/reservas/disponibilidad?sedeId=${encodeURIComponent(locationFilter.value)}&fecha=${date}&tipo=${typeFilter.value}`); if(response.ok) (await response.json()).forEach(item=>occupied.add(`${item.espacioId}|${item.inicio}`)); } catch {} renderGrid(); renderSummary(); }
function renderGrid() { const sede=locationFilter.value; const type=typeFilter.value; const visible=catalog.filter(space=>space.sedeId===sede&&(type==='all'||space.type===type)).slice(0,8); grid.innerHTML=visible.map(space=>`<div class="availability-row"><div class="space-label"><div class="space-mini"></div><div><strong>${space.name}</strong><small>${space.capacity} persona${space.capacity===1?'':'s'}<br>⌖ ${space.location.split('·')[1]}</small></div></div>${times.map(slot=>{const key=`${space.id}|${slot}`;const isOccupied=occupied.has(key)||localOccupied(space.id,slot);const isSelected=selected?.space.id===space.id&&selected.slot===slot;return `<button class="slot ${isOccupied?'occupied':''} ${isSelected?'selected':''}" ${isOccupied?'disabled':''} data-space="${space.id}" data-slot="${slot}">${isSelected?'Seleccionado':isOccupied?'Ocupado':'Disponible'}</button>`}).join('')}</div>`).join('') || '<p class="summary-placeholder">No hay espacios para este filtro.</p>'; }
function renderSummary() { const placeholder=document.querySelector('#summary-placeholder'), content=document.querySelector('#summary-content'); if(!selected){placeholder.hidden=false;content.hidden=true;return} placeholder.hidden=true;content.hidden=false; const {space,slot}=selected; document.querySelector('#summary-type').textContent=space.typeLabel;document.querySelector('#summary-name').textContent=space.name;document.querySelector('#summary-capacity').textContent=space.capacity;document.querySelector('#summary-location').textContent=space.location;document.querySelector('#summary-date').textContent=new Date(`${dateFilter.value}T12:00:00`).toLocaleDateString('es-CO',{day:'numeric',month:'short',year:'numeric'});document.querySelector('#summary-time').textContent=`${slot} - ${String(Number(slot.slice(0,2))+1).padStart(2,'0')}:00`;document.querySelector('#summary-price').textContent=`${money(space.price)} / hora`; }
grid.addEventListener('click',event=>{const button=event.target.closest('.slot');if(!button||button.disabled)return;selected={space:catalog.find(space=>space.id===button.dataset.space),slot:button.dataset.slot};renderGrid();renderSummary();});
document.querySelectorAll('[data-chip]').forEach(chip=>chip.addEventListener('click',()=>{typeFilter.value=chip.dataset.chip;document.querySelectorAll('[data-chip]').forEach(item=>item.classList.remove('active'));chip.classList.add('active');refreshAvailability();}));[locationFilter,typeFilter,dateFilter,timeFilter].forEach(control=>control.addEventListener('change',refreshAvailability));
document.querySelector('#confirm-booking').addEventListener('click',async()=>{if(!selected)return;const start=selected.slot;const end=`${String(Number(start.slice(0,2))+1).padStart(2,'0')}:00`;const body={usuarioId:user.id,espacioId:selected.space.id,fecha:dateFilter.value,inicio:start,fin:end,subtotal:selected.space.price,metodo:0};try{const response=await fetch(`${API}/reservas/confirmar`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!response.ok)throw new Error((await response.json()).error||'No fue posible confirmar');const result=await response.json();location.href=`pagos.html?reservaId=${result.reserva?.id||''}&monto=${result.reserva?.precioTotal||Math.round(selected.space.price*1.19)}&subtotal=${selected.space.price}&espacio=${encodeURIComponent(selected.space.name)}&sede=${encodeURIComponent(selected.space.location)}&fecha=${dateFilter.value}&inicio=${start}&fin=${end}`;}catch(error){location.href=`pagos.html?reservaId=local-${Date.now()}&monto=${Math.round(selected.space.price*1.19)}&subtotal=${selected.space.price}&espacio=${encodeURIComponent(selected.space.name)}&sede=${encodeURIComponent(selected.space.location)}&fecha=${dateFilter.value}&inicio=${start}&fin=${end}`;}});
document.querySelector('#logout').addEventListener('click',()=>{localStorage.removeItem('cospace-user');localStorage.removeItem('cospace-authenticated');});refreshAvailability();
