(() => {
  const sedes = [['sede-centro-mayor','Centro Mayor'],['sede-santa-fe','Centro Comercial Santa Fe'],['sede-plaza-central','Plaza Central'],['sede-mallplaza-nqs','Mallplaza NQS'],['sede-nuestro-bogota','Nuestro Bogotá']];
  const stored = key => JSON.parse(localStorage.getItem(`cospace-${key}`) || 'null');
  const save = (key, value) => localStorage.setItem(`cospace-${key}`, JSON.stringify(value));
  const spaces = [];
  sedes.forEach(([sedeId, sedeName]) => {
    for (let i=1;i<=30;i++) spaces.push({id:`puesto-${sedeId}-${i}`,name:`Puesto ${i}`,sedeId,sedeName,type:'desk',typeLabel:'Escritorio flexible',typeClass:'green',capacity:1,price:12000,dayPrice:45000,location:`${sedeName} · Piso 2, Área abierta`,status:'Activo',statusClass:'active',thumb:'desk'});
    for (let i=1;i<=15;i++) spaces.push({id:`oficina-${sedeId}-${i}`,name:`Oficina ${i}`,sedeId,sedeName,type:'office',typeLabel:'Oficina privada',typeClass:'purple',capacity:2,price:35000,dayPrice:150000,location:`${sedeName} · Piso 2`,status:'Activo',statusClass:'active',thumb:'office'});
    for (let i=1;i<=10;i++) spaces.push({id:`cubiculo-${sedeId}-${i}`,name:`Cubículo ${i}`,sedeId,sedeName,type:'cubicle',typeLabel:'Oficina privada',typeClass:'purple',capacity:4,price:55000,dayPrice:220000,location:`${sedeName} · Piso 2`,status:'Activo',statusClass:'active',thumb:'office'});
    for (let i=1;i<=3;i++) spaces.push({id:`alpha-${sedeId}-${i}`,name:`Sala Alpha ${i}`,sedeId,sedeName,type:'meeting',typeLabel:'Sala de reunión',typeClass:'blue',capacity:6,price:70000,location:`${sedeName} · Piso 3`,status:'Activo',statusClass:'active',thumb:'meeting'});
    for (let i=1;i<=2;i++) spaces.push({id:`beta-${sedeId}-${i}`,name:`Sala Beta ${i}`,sedeId,sedeName,type:'meeting',typeLabel:'Sala de reunión',typeClass:'blue',capacity:8,price:95000,location:`${sedeName} · Piso 3`,status:'Activo',statusClass:'active',thumb:'meeting'});
    spaces.push({id:`gamma-${sedeId}`,name:'Sala Gamma',sedeId,sedeName,type:'meeting',typeLabel:'Sala de reunión',typeClass:'blue',capacity:12,price:130000,location:`${sedeName} · Piso 3`,status:'Activo',statusClass:'active',thumb:'meeting'});
  });
  const users = stored('users') || [{id:'member-demo',nombre:'Sebastián Gil',correo:'sebastian.gil@example.com',telefono:'3000000000',rol:'Miembro',planId:'plan-pro',sedePreferidaId:'sede-centro-mayor'},{id:'admin-demo',nombre:'Laura Gómez',correo:'admin@cospace.co',rol:'Administrador',planId:null,sedePreferidaId:'sede-centro-mayor'},{id:'member-2',nombre:'Mariana Torres',correo:'mariana@example.com',rol:'Miembro',planId:'plan-basico',sedePreferidaId:'sede-santa-fe'},{id:'member-3',nombre:'Daniel Rojas',correo:'daniel@example.com',rol:'Miembro',planId:'plan-empresarial',sedePreferidaId:'sede-plaza-central'},{id:'member-4',nombre:'Sofía Martínez',correo:'sofia@example.com',rol:'Miembro',planId:'plan-pro',sedePreferidaId:'sede-mallplaza-nqs'},{id:'member-5',nombre:'Camilo Pérez',correo:'camilo@example.com',rol:'Miembro',planId:'plan-basico',sedePreferidaId:'sede-nuestro-bogota'},{id:'member-6',nombre:'Valentina Ruiz',correo:'valentina@example.com',rol:'Miembro',planId:'plan-pro',sedePreferidaId:'sede-centro-mayor'},{id:'member-7',nombre:'Nicolás León',correo:'nicolas@example.com',rol:'Miembro',planId:'plan-basico',sedePreferidaId:'sede-santa-fe'}];
  const bookings = stored('bookings') || Array.from({length:18},(_,i)=>({id:`RSV-SEED-${String(i+1).padStart(3,'0')}`,spaceId:spaces[i*7].id,space:spaces[i*7].name,user:users[(i%7)+1].nombre,userId:users[(i%7)+1].id,sedeId:spaces[i*7].sedeId,date:`2026-${String(8+Math.floor(i/9)).padStart(2,'0')}-${String(5+(i%9)).padStart(2,'0')}`,start:'09:00',end:'11:00',status:i%6===0?'Cancelada':i%4===0?'Completada':'Confirmada',total:spaces[i*7].price*2}));
  const payments = stored('payments') || bookings.map((booking,i)=>({invoice:`FAC-SEED-${String(i+1).padStart(4,'0')}`,booking:booking.id,bookingId:booking.id,user:booking.user,userId:booking.userId,amount:Math.round(booking.total*1.19),method:i%2?'PSE':'Tarjeta',status:booking.status==='Cancelada'?'Vencido':i%5===0?'Pendiente':'Pagado',date:booking.date,sedeId:booking.sedeId,space:booking.space}));
  save('users',users); save('bookings',bookings); save('payments',payments);
  window.CoSpaceStore = {sedes, spaces: stored('spaces') || spaces, users, bookings, payments, save};
})();
